name: Billing & Payments Suggestion Box Template
description: Suggestions to Money Support Operations regarding Billing & Payments
title: " [Date - MMM.DD/YY] - [Suggestion:Billing/Payments/Installments/Other]: Title "
labels: ["Suggestion"]
assignees:
  -   -
body:
  - type: markdown
    attributes:
      value: |
        **Please update the title to reflect [Date][Suggestion topic] Brief title.  Ex: [Jan. 4/22] [Payments] Change to Money Support Operations Playbook**
-    -  
  - type: dropdown
    id: Topic
    attributes:
      label: This Suggestion Pertains to
      description: Please indicate the product this suggestion is related to (Billing, Payments, Installments, or Other)
      options:
        - Billing
        - Payments
        - Installments
        - Other
    validations:
      required: true
  - type: textarea
    id: suggestion-summary
    attributes:
      label: Suggestion Summary
      description: A quick TLDR of your suggestion
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details and Links
      description: Please describe your suggestion and include any relevant links
    validations:
      required: true
  - type: dropdown
    id: help
    attributes:
      label: I would like to work on this project if help is needed
      description:
      options:
        - "Yes"
        - "No"
    validations:
      required: true
